server:
  port: 8003

spring:
  application:
    name: feign-consumer #服务名
  profiles:
    active: dev #环境设置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务注册

  main:
    allow-bean-definition-overriding: true


